### PR TITLE
Added orbit option to Stage and World to enable OrbitControls

### PR DESCRIPTION
**Pull request by jlstevens**
This pull request adds an option to enable OrbitControls as proposed in issue #11. To enable OrbitControls, you simply need to set `orbit` to `false` in the `Stage` options (or the `World` options if used directly).

I should note that this requires a more recent version of three.js than used by the demos listed in the README   (r66). A recent version of three.js  (r72) has been tested and seems to work nicely.

If you have any suggestions for further improvements I would be very happy to implement them!

### CODE REVIEW

**Comment by domitry** [comment]
Sorry for my delayed replay. 

This pull-req is awesome! Thank you! BTW can you add a new example to examples/ ? I checked the new option on my local environment, but files under examples/ are substitutes for GUI-test.

**Comment by jlstevens** [comment]
I've made a few minor fixes and added `examples/orbit.html` based on the existing `surface.html` example. If there is anything else you would like to see improved, do let me know!

**Comment by domitry** [comment]
Thanks @jlstevens it looks perfect for me.
BTW I can't spend time for the development of Elegans enough, so I added you to Collaborator.
If you'd like to add more code push it by yourself !

**Comment by jlstevens** [comment]
I do have some outstanding prototypes for new features that just need cleaning up. I will continue to propose any larger additions as pull requests but it is nice to also have merge rights and a chance to make small fixes directly when necessary. :-)

Thank you very much!

**Pull request merged**
